{{ if .Values.dataPersistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metersphere-data-pvc
spec:
  accessModes:
    - {{.Values.logPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.logPersistence.size}}
  storageClassName: {{.Values.common.storageClass}}
{{end}}